name: UPPM builds and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build uppm.phar
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        php8.0 target/uppm.phar install
        php8.0 target/uppm.phar lock

    - name: Building
      run: |
        sudo chmod 777 /etc/php/8.0/cli/php.ini
        sudo echo phar.readonly = Off >> /etc/php/8.0/cli/php.ini
        php8.0 src/main/bootstrap.php build
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Building UPPM
      run: |
        sudo chmod 777 /etc/php/8.0/cli/php.ini
        sudo echo phar.readonly = Off >> /etc/php/8.0/cli/php.ini
        php8.0 uppm.phar install
        php8.0 src/main/bootstrap.php build
        chmod +x ./target/uppm.phar
      
    - name: Install packages
      run: ./target/uppm.phar install
    
    - name: Getting autoload
      run: ./target/uppm.phar autoload

    - name: Creating Project and testing it
      run: |
        ./target/uppm.phar create test
        cd test
        ../target/uppm.phar install deverm
        ../target/uppm.phar install interaapps/ulole-orm+master@github
        ../target/uppm.phar install
        ../target/uppm.phar lock
        ../target/uppm.phar run start
        echo \n
        sudo chmod 777 /etc/php/8.0/cli/php.ini
        sudo echo phar.readonly = Off >> /etc/php/8.0/cli/php.ini
        ../target/uppm.phar build
        chmod +x target/test-1.0.phar
        ./target/test-1.0.phar
